version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  # BeforeInstall:
  #   - location: scripts/before_teste.sh
  #     timeout: 300
  #     runas: root
  # # AfterInstall:
  # #   - location: scripts/after_teste.sh
  # #     timeout: 300
  # #     runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  # ApplicationStop:
  #   - location: scripts/stop_teste.sh
  #     timeout: 300
  #     runas: ec2-user